#!/usr/bin/env bash
set -euo pipefail

branch="${1:-main}"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "[safe-pull] Not inside a git repository" >&2
  exit 1
fi

echo "[safe-pull] Preparing working tree for pull on branch: ${branch}"

# Reset tracked build artifacts that are frequently modified by local builds.
# This covers both manifest files and tracked hashed assets from prior commits.
git restore --worktree --staged \
  bootstrap/ssr/assets \
  bootstrap/ssr/ssr-manifest.json \
  bootstrap/ssr/ssr.js \
  public/build/assets \
  public/build/manifest.json 2>/dev/null || true

# Remove untracked hashed assets generated by local builds.
if [ -d bootstrap/ssr/assets ]; then
  git clean -fd bootstrap/ssr/assets
fi
if [ -d public/build/assets ]; then
  git clean -fd public/build/assets
fi

echo "[safe-pull] Pulling latest changes"
git pull --ff-only origin "${branch}"

echo "[safe-pull] Done. Next recommended steps:"
echo "  php artisan migrate --force"
echo "  npm run build"
echo "  php artisan optimize:clear"
