[program:zyptos-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /home2/zyptosco/zyptos_app/artisan queue:work database --queue=default,chatbots,campaigns --sleep=1 --tries=3 --timeout=120 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=zyptosco
numprocs=1
redirect_stderr=true
stdout_logfile=/home2/zyptosco/zyptos_app/storage/logs/queue-worker.log
stopwaitsecs=130
