// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxgpSL5Qsiu8bwZx-wXjHBEmrkrTD8S8A',
    appId: '1:930709255787:android:e31af25b224194a624e32e',
    messagingSenderId: '930709255787',
    projectId: 'studio-8062470255-fcdb7',
    storageBucket: 'studio-8062470255-fcdb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGYE3i-KEHyjTuaPrpzH5eqOUwfsgTOQ',
    appId: '1:930709255787:ios:08a1dfa4c34f999524e32e',
    messagingSenderId: '930709255787',
    projectId: 'studio-8062470255-fcdb7',
    storageBucket: 'studio-8062470255-fcdb7.firebasestorage.app',
    iosClientId:
        '930709255787-qpokdsm2lm59888i25kjgon3hee84ffh.apps.googleusercontent.com',
    iosBundleId: 'com.zyptos.mobile',
  );
}
